### PR TITLE
Explanations page Table of Contents

### LINKED ISSUE #113: Add Table of Contents to explanations page
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I can't find what I look for on the explanations page.

### Describe the solution you'd like

I would like to see a table of contents so I can easily navigate there.

### Additional context

I like how Wikipedia has a sticky ToC:
image

### PR DESCRIPTION
**Pull request by chucker**
fixes #113

- [x] move to left-hand side
- create a minified version of MudBlazor with just this one service?
- [x] less prominent color; no blue hyperlinks

### CODE REVIEW

**Comment by chucker** [comment]
I'm unsure about the dependency. It's quite heavy, and we only really need one service from it. But forking it also means continuous maintenance.

**Comment by chucker** [comment]
Oh, and this doesn't support multiple layers of headers. I think we don't really need that, for now.

**Comment by ricardoboss** [comment]
> I'm unsure about the dependency. It's quite heavy, and we only really need one service from it. But forking it also means continuous maintenance.

Yeah, really not a fan of a _second_ component library. I also agree adding more code than necessary means more maintenance for us.

Not sure if a ToC is worth the effort of maintaining either of those solutions...

**Comment by chucker** [comment]
>I also agree adding more code than necessary means more maintenance for us.

Yeah.

There's a third solution of "offer a PR to MudBlazor that provides a NuGet with must this one service". But I don't really want to put that work in.

I _might_ look into manually tree-shaking this stuff. A fork that throws must MudBlazor code out and just leaves the code we need. Not sure how much work that is, though.

How about option four: petition Blazorise to offer a MudBlazor-like scroll handler?

>Apart from that it looks and functions as expected. GJ

:)

**Comment by ricardoboss** [comment]
This needs to be rebased (a version was already release since this was opened). Afterwards, we can merge this, I think

**Review by ricardoboss — APPROVED** [review]

**Pull request merged**
