### PR TITLE
Explain most paradigms; clean up Explanations page

### PR DESCRIPTION
**Pull request by chucker**
A few more remarks:

- I propose getting rid of `TaskDriven`. Wikipedia just links to https://en.wikipedia.org/w/index.php?title=The_Task-based_Asynchronous_Pattern&redirect=no, which is barely an article, and describes more an API than a language feature. C# is already marked concurrent.
- I'm still not sure how to make the explanations page pop. I was wondering if we need to parse Markdown or HTML in `[Description]`; that might help. The layout is overall still too wide and too sparse, I think.
- I'm struggling to explain OOP. :-) A lot of explanations talk about classes, but not all OOP classes have those.

### CODE REVIEW

**Comment by chucker** [comment]
>I was wondering if we need to parse Markdown or HTML in [Description]; that might help.

This also relates to https://github.com/ricardoboss/Prolangle/issues/10#issuecomment-1879366528

**Comment by chucker** [comment]
See also #86

**Comment by ricardoboss** [comment]
> I propose getting rid of TaskDriven

Agreed. Go ahead and remove it

**Comment by ricardoboss** [comment]
I'd add more spacing between the area headers (more margin above "Known for building / Applications" and "Syntax styles" and so on).

Also, the width of the content should be limited to `80ch`, IMHO.

**Comment by chucker** [comment]
> I'd add more spacing between the area headers (more margin above "Known for building / Applications" and "Syntax styles" and so on).
> 
> Also, the width of the content should be limited to `80ch`, IMHO.

Done!

**Pull request merged**
